name: TerraPVPArena
version: 1.0
authors:
  - Eli Watkins
  - Micaiah Landis
main: dev.terra.terraminigames.Main
api-version: 1.14
commands:
  kills:
    description: Gets number of kills for a player
    usage: /kills <playername(optional)>